/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OurOOPProject;

import project2020new.ProjectInterfaces.*;

/**
 *
 * @author Marya Alamzeb
 */
public class AdminModules extends javax.swing.JFrame {

    /**
     * Creates new form AdminModules
     */
    public AdminModules() {
        initComponents();
    }
   public void setMain(Main m)
    {
        main=m;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aboutb = new javax.swing.JButton();
        termsb = new javax.swing.JButton();
        addroutesb5 = new javax.swing.JButton();
        Helpb = new javax.swing.JButton();
        Homeb = new javax.swing.JButton();
        addroutesb4 = new javax.swing.JButton();
        addroutesb = new javax.swing.JButton();
        addroutesb1 = new javax.swing.JButton();
        addroutesb3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        addroutesb2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homeb = new javax.swing.JButton();
        updaterb = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addrateb = new javax.swing.JButton();

        Aboutb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Aboutb.setText("About");
        Aboutb.setBorder(null);

        termsb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        termsb.setText("Terms of service");
        termsb.setBorder(null);

        addroutesb5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addroutesb5.setText("Log out");
        addroutesb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroutesb5ActionPerformed(evt);
            }
        });

        Helpb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Helpb.setText("Help");
        Helpb.setBorder(null);

        Homeb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Homeb.setText("Home");
        Homeb.setBorder(null);

        addroutesb4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addroutesb4.setText("Back");
        addroutesb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroutesb4ActionPerformed(evt);
            }
        });

        addroutesb.setBackground(new java.awt.Color(204, 204, 204));
        addroutesb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addroutesb.setText("Add routes");
        addroutesb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroutesbActionPerformed(evt);
            }
        });

        addroutesb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addroutesb1.setText("Delete routes");
        addroutesb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroutesb1ActionPerformed(evt);
            }
        });

        addroutesb3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addroutesb3.setText("Delete packages");
        addroutesb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroutesb3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        addroutesb2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addroutesb2.setText("Show packages");
        addroutesb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroutesb2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Manage Admin Modules");

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        homeb.setBackground(new java.awt.Color(0, 0, 0));
        homeb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeb.setForeground(new java.awt.Color(255, 255, 255));
        homeb.setText("HOME");
        homeb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        homeb.setBorderPainted(false);
        homeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(homeb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        updaterb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updaterb.setText("Show routes");
        updaterb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updaterbActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addrateb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addrateb.setText("Show Rate List");
        addrateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addratebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(83, 83, 83))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addrateb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addroutesb2)
                    .addComponent(updaterb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updaterb)
                .addGap(32, 32, 32)
                .addComponent(addroutesb2)
                .addGap(37, 37, 37)
                .addComponent(addrateb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(51, 51, 51)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addroutesbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroutesbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addroutesbActionPerformed

    private void addroutesb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroutesb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addroutesb1ActionPerformed

    private void addroutesb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroutesb2ActionPerformed
        // TODO add your handling code here:
        new ViewOffers().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addroutesb2ActionPerformed

    private void addroutesb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroutesb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addroutesb3ActionPerformed

    private void addroutesb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroutesb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addroutesb4ActionPerformed

    private void addroutesb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroutesb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addroutesb5ActionPerformed

    private void homebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebActionPerformed
        // TODO add your handling code here:
        
         new Main().setVisible(true);
        
        this.dispose();
       
    }//GEN-LAST:event_homebActionPerformed

    private void updaterbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updaterbActionPerformed
        // TODO add your handling code here:
        
        new ServiceRecord().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updaterbActionPerformed

    private void addratebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addratebActionPerformed
        // TODO add your handling code here:
      new RateLists().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addratebActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Managemodules().setVisible(true);
        this .setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModules().setVisible(true);
            }
        });
    }
private Main main;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aboutb;
    private javax.swing.JButton Helpb;
    private javax.swing.JButton Homeb;
    private javax.swing.JButton addrateb;
    private javax.swing.JButton addroutesb;
    private javax.swing.JButton addroutesb1;
    private javax.swing.JButton addroutesb2;
    private javax.swing.JButton addroutesb3;
    private javax.swing.JButton addroutesb4;
    private javax.swing.JButton addroutesb5;
    private javax.swing.JButton homeb;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton termsb;
    private javax.swing.JButton updaterb;
    // End of variables declaration//GEN-END:variables
}
